name = "elphbolt"
license = "GPLv3+"
author = "Nakib Haider Protik"
maintainer = "nakib.haider.protik@gmail.com"
copyright = "2023 Contributors of the elphbolt project."

[fortran]
implicit-external = true #Needed for v>=0.7 fpm

[library]
source-dir="src"

[preprocess]
[preprocess.cpp]

[dependencies]
#Pull from github
#testify = { git = "git@github.com:nakib/testify.git" }
testify = {path = "thirdparty/testify"}
fhash = { git = "https://github.com/LKedward/fhash.git" }

#Use local copy from thirdparty directory
spglib = {path = "thirdparty/spglib"}

[build]
#[build]
#By default, I will use try to use the forlapack and forblas builds from ~/.local/lib/
#These will have been put there by the configuration step.
link = ["forlapack", "forblas"]
#
#Alternatively, you can use your preexisting blas and lapack, or openblas,
#or whatever other implementation by commenting out the above and uncommenting
#one of the following. Modify according to your system.
#link = ["blas", "lapack"]
#link = ["openblas"]

external-modules = ["openacc"]
auto-tests = false

[install]
library = true

[[executable]]
name="elphbolt"
source-dir="app"
main="elphbolt.f90"

[[executable]]
name="superconda"
source-dir="app"
main="superconda.f90"

[[test]]
name = "test_misc"
source-dir="test"
main = "test_misc.f90"

[[test]]
name = "test_autodiff"
source-dir="test"
main = "test_autodiff.f90"

[[test]]
name = "bte_regression"
source-dir="test"
main = "bte_regression.f90"

