name: build_test_fpm

on: [pull_request, push]

jobs:
  Build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04]
    env:
      GCC_V: 12

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - uses: fortran-lang/setup-fpm@v5
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Install dependencies
      if: contains( matrix.os, 'ubuntu')
      run: |
        sudo apt update
        sudo apt install -yq cmake gfortran mpich
        sudo apt clean -q
        git clone https://github.com/sourceryinstitute/OpenCoarrays && \
        mkdir OpenCoarrays/opencoarrays-install  && \
        cd OpenCoarrays/opencoarrays-install && \
        git checkout tags/2.10.1 && \
        FC="$(command -v gfortran)" CC="$(command -v gcc)" cmake .. && \
        sudo make install && \
        caf --version && \
        cafrun --version
        
    - name: Build with fpm
      run: |
        sh install_blas+lapack.sh
        source fpm_config_caf.sh
        fpm build; fpm install && \
        fpm test test_autodiff test_misc test_periodictable && \
        fpm test test_vector_allreps && \
        fpm test bte_regression --runner="sh test/3C-SiC/fpm_run_bte_caf.sh"
