name: build_test_cmake

on: [pull_request, push]

jobs:
  Build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
    env:
      GCC_V: 9

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v1.8

    - name: Install dependencies
      if: contains( matrix.os, 'ubuntu')
      run: |
        sudo apt update
        sudo apt install -yq cmake gfortran-9 mpich liblapack-dev libsymspg-dev
        sudo apt clean -q
        git clone https://github.com/sourceryinstitute/OpenCoarrays && \
        mkdir OpenCoarrays/opencoarrays-install  && \
        cd OpenCoarrays/opencoarrays-install && \
        git checkout tags/2.10.1 && \
        FC="$(command -v gfortran-9)" CC="$(command -v gcc-9)" cmake .. && \
        sudo make install && \
        caf --version && \
        cafrun --version
        
    - name: Build with CMake
      run: |
        mkdir build; cd build
        cmake ..; make; ctest --rerun-failed --output-on-failure
